### ISSUE TITLE
Constructor property promotion

### ISSUE THREAD

**Issue by rhoerr** [mage-os-lab/web-installer#8]
Reviewing code: `src/Magento/Setup/Controller/Environment.php` uses constructor property promotion. I didn't notice any other instances. Is this fine, or best avoided still?

I haven't tried it, but I wonder if this (in and of itself?) would prevent a friendly error page if you try to install on PHP 7.4.

```php
    public function __construct(
        protected \Magento\Framework\Setup\FilePermissions $permissions,
        protected \Magento\Framework\Filesystem $filesystem,
        protected \Magento\Setup\Model\CronScriptReadinessCheck $cronScriptReadinessCheck,
        protected \Magento\Setup\Model\PhpReadinessCheck $phpReadinessCheck
    ) {
    }
```

**Comment by jakwinkler** [comment]
Latest Magento requires PHP 8.1, I can `downgrade` this to PHP7.4
Imho, PHP8.1 should be the minimum requirement

**Comment by rhoerr** [comment]
Overall, Mage-OS' current minimum PHP version is 8.1, same as Magento 2.4.7. But if someone tries running it on 7.4, what happens? And does this code impact that, or is it the same either way?

If it just shows a message 'PHP 8.1+ required' (which has been my experience in the past), unrelated to the installer, then we should just allow this usage, close the issue, and move on.

If it shows an error _due to this code_, I think we should make the code backwards compatible a bit more and let the compatibility checker handle it.

**Comment by rhoerr** [comment]
I'm going to close this. Mage-OS 1.0.0+'s minimum supported version is 8.1 via composer, meaning anyone trying to install on an older version of PHP will hit an error before they can even do the composer install, much less access the web installer. To bypass that they would either have to explicitly ignore the platform reqs (probably causing other errors), or require `web-installer` with an older version of Magento, and there's no good reason for someone to be creating a new install on an old version of Magento.

As such, I think it's reasonable for `web-installer` to have PHP 8.1 syntax.
